// Code generated by `ubx blueprint build`. DO NOT EDIT.
package ciplatform

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ContainerRepoConfig struct {
	ImageScanningConfiguration any
	ImageTagMutability any
	Name any
}

var ContainerRepo = sdk.ResourceBinding{
	WireType: "aws_ecr_repository",
	Fields: sdk.FieldMap{
		"ImageScanningConfiguration": sdk.FieldSpec{WireName: "image_scanning_configuration"},
		"ImageTagMutability": sdk.FieldSpec{WireName: "image_tag_mutability"},
		"Name": sdk.FieldSpec{WireName: "name"},
	},
}

type PipelineEventsConfig struct {
	MessageRetentionSeconds any
	Name any
}

var PipelineEvents = sdk.ResourceBinding{
	WireType: "aws_sqs_queue",
	Fields: sdk.FieldMap{
		"MessageRetentionSeconds": sdk.FieldSpec{WireName: "message_retention_seconds"},
		"Name": sdk.FieldSpec{WireName: "name"},
	},
}

type CiRunnerConfig struct {
	AssumeRolePolicy any
	Name any
}

var CiRunner = sdk.ResourceBinding{
	WireType: "aws_iam_role",
	Fields: sdk.FieldMap{
		"AssumeRolePolicy": sdk.FieldSpec{WireName: "assume_role_policy"},
		"Name": sdk.FieldSpec{WireName: "name"},
	},
}

type CiRunnerAccessConfig struct {
	Name any
	Policy any
}

var CiRunnerAccess = sdk.ResourceBinding{
	WireType: "aws_iam_policy",
	Fields: sdk.FieldMap{
		"Name": sdk.FieldSpec{WireName: "name"},
		"Policy": sdk.FieldSpec{WireName: "policy"},
	},
}

type CiRunnerAccessAttachmentConfig struct {
	PolicyArn any
	Role any
}

var CiRunnerAccessAttachment = sdk.ResourceBinding{
	WireType: "aws_iam_role_policy_attachment",
	Fields: sdk.FieldMap{
		"PolicyArn": sdk.FieldSpec{WireName: "policy_arn"},
		"Role": sdk.FieldSpec{WireName: "role"},
	},
}

