// Code generated by `ubx blueprint build`. DO NOT EDIT.
package ciplatform

import (
	sdk "github.com/ubiquex/ubx-sdk-go/runtime"
)

// Option overrides one params: default value not explicitly passed by the caller.
type Option func(*options)

type options struct {
	retentionDays int
}

// WithRetentionDays overrides the "retention_days" params: default.
func WithRetentionDays(v int) Option {
	return func(o *options) { o.retentionDays = v }
}

func CiPlatform(repoName string, queueName string, opts ...Option) {
	cfg := options{
		retentionDays: 1,
	}
	for _, opt := range opts {
		opt(&cfg)
	}

	containerRepo := sdk.Resource(ContainerRepo, "container-repo", ContainerRepoConfig{
		ImageScanningConfiguration: map[string]any{"scan_on_push": true},
		ImageTagMutability: "IMMUTABLE",
		Name: repoName,
	})
	pipelineEvents := sdk.Resource(PipelineEvents, "pipeline-events", PipelineEventsConfig{
		MessageRetentionSeconds: cfg.retentionDays * 86400,
		Name: queueName,
	})
	ciRunner := sdk.Resource(CiRunner, "ci-runner", CiRunnerConfig{
		AssumeRolePolicy: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"ec2.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}",
		Name: "ci-runner",
	})
	ciRunnerAccess := sdk.Resource(CiRunnerAccess, "ci-runner-access", CiRunnerAccessConfig{
		Name: "ci-runner-access",
		Policy: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":[\"ecr:GetDownloadUrlForLayer\",\"ecr:BatchGetImage\",\"ecr:BatchCheckLayerAvailability\",\"ecr:PutImage\",\"ecr:InitiateLayerUpload\",\"ecr:UploadLayerPart\",\"ecr:CompleteLayerUpload\"],\"Resource\":" + "{\"$ref\":{\"to\":\"" + containerRepo.Field("arn").Address() + "\"}}" + "},{\"Effect\":\"Allow\",\"Action\":[\"ecr:GetAuthorizationToken\"],\"Resource\":\"*\"},{\"Effect\":\"Allow\",\"Action\":[\"sqs:SendMessage\"],\"Resource\":" + "{\"$ref\":{\"to\":\"" + pipelineEvents.Field("arn").Address() + "\"}}" + "}]}",
	})
	sdk.Resource(CiRunnerAccessAttachment, "ci-runner-access-attachment", CiRunnerAccessAttachmentConfig{
		PolicyArn: ciRunnerAccess.Field("arn"),
		Role: ciRunner.Field("name"),
	})
}
