// Code generated by `ubx blueprint build`. DO NOT EDIT.
package ciplatform

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ContainerRepoConfig struct {
	ImageScanningConfiguration any
	ImageTagMutability any
	RepositoryName any
}

var ContainerRepo = sdk.ResourceBinding{
	WireType: "aws_ecr_repository",
	Fields: sdk.FieldMap{
		"ImageScanningConfiguration": sdk.FieldSpec{WireName: "image_scanning_configuration"},
		"ImageTagMutability": sdk.FieldSpec{WireName: "image_tag_mutability"},
		"RepositoryName": sdk.FieldSpec{WireName: "repository_name"},
	},
	BlueprintName: "ci-platform",
}

type PipelineEventsConfig struct {
	MessageRetentionPeriod any
	QueueName any
}

var PipelineEvents = sdk.ResourceBinding{
	WireType: "aws_sqs_queue",
	Fields: sdk.FieldMap{
		"MessageRetentionPeriod": sdk.FieldSpec{WireName: "message_retention_period"},
		"QueueName": sdk.FieldSpec{WireName: "queue_name"},
	},
	BlueprintName: "ci-platform",
}

type CiRunnerConfig struct {
	AssumeRolePolicyDocument any
	RoleName any
}

var CiRunner = sdk.ResourceBinding{
	WireType: "aws_iam_role",
	Fields: sdk.FieldMap{
		"AssumeRolePolicyDocument": sdk.FieldSpec{WireName: "assume_role_policy_document"},
		"RoleName": sdk.FieldSpec{WireName: "role_name"},
	},
	BlueprintName: "ci-platform",
}

type CiRunnerAccessConfig struct {
	PolicyDocument any
	PolicyName any
	Roles any
}

var CiRunnerAccess = sdk.ResourceBinding{
	WireType: "aws_iam_policy",
	Fields: sdk.FieldMap{
		"PolicyDocument": sdk.FieldSpec{WireName: "policy_document"},
		"PolicyName": sdk.FieldSpec{WireName: "policy_name"},
		"Roles": sdk.FieldSpec{WireName: "roles"},
	},
	BlueprintName: "ci-platform",
}

